#version: '3.8'
#services:
#  mysql:
#    image: 'mysql:latest'
#    environment:
#      - MYSQL_ROOT_PASSWORD=hau
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=
#      - MYSQL_DATABASE=microservice-db
#    ports:
#      - '3309:3306'
#    volumes:
#      - mysql-services-volume:/var/lib/mysql
#
#  rabbitmq:
#    image: 'rabbitmq:latest'
#    environment:
#      - RABBITMQ_DEFAULT_PASS=secret
#      - RABBITMQ_DEFAULT_USER=myuser
#    ports:
#      - '5672:5672'
#
#volumes:
#  mysql-services-volume:
